### ISSUE TITLE
[BoxWhiskerPlot] Too much data error on small dataset

### ISSUE THREAD

**Issue by KevinHoward** [liprec/PowerBI-custom-visuals#2]
Hi Jan!

First off, your Power BI Box-Whisker Plot visualization is stellar. Great work!

My team is trying to use this visualization against a relatively small dataset (20 columns with 1,400 rows), however, we are getting an error stating the data set is too large. 

Being the curious guy I am, I jumped into the code and noticed that it's using the passed in dataView.matrix to populate your data points and categories [#L353](https://github.com/liprec/PowerBI-custom-visuals/blob/master/oldAPI/boxWhiskerChart/visual/boxWhiskerChart.ts#L353). What caught my eye with this line though is that the Categories are populated from the rows property and not the columns. 

I am not an expert on TypeScript or Power BI visualizations and may be missing something that's obvious, but shouldn't it be the opposite to avoid any column count limitations with the underlying matrix?  I would think that the Categories should run across, not down in the dataset. 

When we create a matrix in Power BI against the same dataset and flip the axis, we receive the same error message.

**Comment by liprec** [comment]
Hi @KevinHoward,

My visual is designed to get a dataset with one measure (Values), one category field (Groups) for the number of box and whiskers and several fields that 'samples'  the dataset (Samples). There are some data point limitations: category can have a maximum of 100 and the sampling has a maximum of 50.000.

So probably the column your are using as the category/groups field has to many individual values and due to the maximum of 100 it will hit the limit and Power BI warns that the 'dataset is too large'.

And the main reason of mapping the categories to the rows of the matrix, is that all assigned datapoints (columns) can be retrieved via an array ([#L385](https://github.com/liprec/PowerBI-custom-visuals/blob/162a113225543e62b8148d50b0375341db50f1c6/oldAPI/boxWhiskerChart/visual/boxWhiskerChart.ts#L385)) and this array is used to calculate the measures needed for the box and whisker.

Hope this will help you. If not maybe you can share your dataset so it would be easier to pinpoint what is causing the warning. 

Thanks, JP

**Comment by KevinHoward** [comment]
@liprec ,

I did some further investigation, and it appears that the error only occurs when the data source is an SSAS Tabular Model. When pulling the same data from an Excel file, everything works as expected. So, it appears that this error is caused by something in Power BI and not in the visualization.

Thanks for your help.

-Kevin

same issues: 
[http://community.powerbi.com/t5/Service/Too-Many-Values-Not-Showing-All-Data-error-for-pie-chart/td-p/3294](http://community.powerbi.com/t5/Service/Too-Many-Values-Not-Showing-All-Data-error-for-pie-chart/td-p/3294)
[http://community.powerbi.com/t5/Desktop/Too-many-values/td-p/2939](http://community.powerbi.com/t5/Desktop/Too-many-values/td-p/2939)
